### ISSUE TITLE
$To-do~List·$任务清单 | Orchidany'w blog

### ISSUE THREAD

**Issue by Flower233pks** [Flower233pks/Flower233pks.github.io#7]
http://www.orchidany.cf/2019/02/12/To-do-List/#more 

 Emmm…Due to my poor executive force, I plan to make this table for myself ans for u, to show what I’m doing and what I’m gonna do. Praying, this way will help a bit :) And…From one task was accomplish

**Comment by menhood** [comment]
安装的时候有报错吗，我在源码里好像没找到aplayer的样式表

**Comment by Flower233pks** [comment]
![image](https://user-images.githubusercontent.com/42432004/52761138-33bab580-304d-11e9-8bf4-5d8cb93a2606.png)
如果这算报错的话……

**Comment by menhood** [comment]
看起来没啥问题呀，是不是生成的时候出问题了 ~~菜是原罪，太菜看不出问题 [捂脸]~~

**Comment by Flower233pks** [comment]
QAQ
